# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy'
        required: true
        default: 'Sandbox'
        options:
          -  'Sandbox'
          -  'Quality'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set Environment
        run: echo "DEPLOY_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!. $VAR1

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          DEPLOY_ENV: ${{ env.DEPLOY_ENV }}
        run: |
          # You can now use $DEPLOY_ENV in your deployment steps
          if [ "$DEPLOY_ENV" == "Sandbox" ]; then
            # Print the value of VAR1 for the Sandbox environment
            echo "VAR1 in Sandbox: $VAR1"
          elif [ "$DEPLOY_ENV" == "Quality" ]; then
            # Print the value of VAR1 for the Quality environment
            echo "VAR1 in Quality: $VAR1"
          else
            # Handle other cases
          fi
