name: Code Push Trigger

on:
  push:
    branches:
      - main
      - sandbox
      - quality

jobs:
  build:
    runs-on: ubuntu-latest
    environment: $BRANCH_NAME
    env:
      BRANCH_NAME: ${{ github.event.ref }}

    steps:
      - name: Checkout code
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, ${{ github.event.ref }}world!.    