name: Code Push Trigger

on:
  push:
    branches:
      - main
      - sandbox
      - quality

jobs:
  build:
    runs-on: ubuntu-latest
    environment: $BRANCH_NAME
    env:
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - name: Checkout code
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3


      # Runs a single command using the runners shell
      - name: Run a 1st script
        run: echo Hello, ${{ github.ref_name }} world!. 

      - name: Run a 2nd script
        run: echo this ${{ secrets.SECRET1 }}
        
      - name: Run a 3rd script
        run: echo this ${{ vars.VAR1 }}   